name: ADB Automation

on:
  push:
    branches:
      - main

jobs:
  run_adb_script:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Update packages and install ADB
      run: |
        sudo apt-get update
        sudo apt-get install android-tools-adb

    - name: Run ADB Automation script
      run: |
        bash run.sh
